version: "3"

name: cassiopee_prodution

services:
  reverse-proxy:
    restart: always
    build:
      args:
        - host_arg=${HOST}
    # image: ghcr.io/cassiopee-bureau-mobile/cassiopee-reverse-proxy:${tag:-latest}
    volumes:
      - ./ssl/${HOST}.crt:/etc/nginx/ssl/${HOST}.crt
      - ./ssl/${HOST}.key:/etc/nginx/ssl/${HOST}.key

  frontend:
    restart: always
    build:
      args:
        - next_public_base_url=https://${HOST}
    # image: ghcr.io/cassiopee-bureau-mobile/cassiopee-frontend:${tag:-latest}
    environment:
      - NEXTAUTH_URL=https://${HOST}
    expose:
      - 3000
    volumes:
      - ../ansible:/etc/ansible
      - ../logs:/logs

  database:
    restart: always
    expose:
      - 5432
